### ISSUE TITLE
Please make gTTS optional and state the requirements in the README

### ISSUE THREAD

**Issue by DidierSpaier** [apeitheo/aletheia#20]
I built successfully from git, thanks. However I came across two hurdles:

1. The function check_dep looks for a command in $PATH, but if we miss one this doesn't say the name of the missing package. As an example it took me some time to find that gtts-cli is shipped in the gTTS python package, not available for Slackware and Slint. Other example, here "command -v isnum" returns nothing and i do not which package I should build and install to get it. Adding a list of dependencies as packages names in the README would help to find that, possibly using  https://repology.org/
2.  Maybe gTTS could be made optional?

PS. Through a query in the Debian packages: https://packages.debian.org/search?searchon=contents&keywords=isnum&mode=exactfilename&suite=bookworm&arch=any I have found that /usr/bin/isnum is shipped in the package wcstools, not available for Slackware or Slint either. Can we do without it?

Cheers,
Didier

**Comment by apeitheo** [comment]
I hope the latest update covers most of it. It no longer checks for gtts-cli unless USE_GTTS is true in ~/.aletheia/config. Likewise with 'parallel' and 'play' and just warns during install.

I included a list of the packages necessary from SlackBuilds.org and wrote my own version of isnum, so we no longer require wcs-tools.

Thank you for the help.

Brad
